name: chess
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pylint
  - pytest
  - sphinx
  - numpy
  - jupyterlab
  - ipywidgets
  - matplotlib
  - chess
  - pip
  - pip:
    - cachetools
    - sphinx_rtd_theme
